import {Routes,Route,Link,useNavigate}from"react-router-dom";import{LayoutDashboard,Package,Boxes,Users,ClipboardList,MessageSquare,PawPrint,Plus,LogOut}from"lucide-react";import{useAuth}from"../context/AuthContext";import{useEffect,useState}from"react";import api from"../services/api";

function Shell(){const{user,logout}=useAuth(),nav=useNavigate();return <div className="admin-layout"><aside className="admin-sidebar"><Link className="admin-brand" to="/admin"><PawPrint/> DomesticCare <small>ADMIN</small></Link><nav><Link to="/admin"><LayoutDashboard/> Dashboard</Link><Link to="/admin/products"><Boxes/> Products & stock</Link><Link to="/admin/animals"><PawPrint/> Animals</Link><Link to="/admin/orders"><ClipboardList/> Orders</Link><Link to="/admin/users"><Users/> Users</Link><Link to="/admin/inquiries"><MessageSquare/> Inquiries</Link></nav><button className="admin-logout" onClick={()=>{logout();nav("/")}}><LogOut/> Logout</button></aside><section className="admin-content"><Routes><Route index element={<Dashboard/>}/><Route path="products" element={<ProductManager/>}/><Route path="animals" element={<AnimalManager/>}/><Route path="orders" element={<OrderManager/>}/><Route path="users" element={<UsersManager/>}/><Route path="inquiries" element={<InquiryManager/>}/></Routes></section></div>}

function Dashboard(){const[d,setD]=useState(null);useEffect(()=>{api.get("/admin/dashboard").then(r=>setD(r.data))},[]);return <div><div className="admin-top"><div><span className="eyebrow">Control centre</span><h1>Admin dashboard</h1></div><Link className="btn primary" to="/admin/products"><Plus/> Add product</Link></div><div className="stat-grid">{[["Users",d?.users,"👥"],["Products",d?.products,"🛍️"],["Animals",d?.animals,"🐾"],["Orders",d?.orders,"📦"],["Low stock",d?.lowStock,"⚠️"],["Revenue",`₹${(d?.revenue||0).toLocaleString("en-IN")}`,"₹"]].map(([a,b,c])=><div className="stat" key={a}><span>{c}</span><small>{a}</small><strong>{b??"—"}</strong></div>)}</div><div className="admin-callout"><b>Inventory rule:</b> stock 0 automatically appears as Out of Stock and prevents customer cart additions. Stock 1–5 is shown as Low Stock.</div></div>}

function ProductManager(){const[items,setItems]=useState([]),[edit,setEdit]=useState(null),[msg,setMsg]=useState("");const blank={name:"",category:"Animal Feed",animalCategory:"General",image:"",description:"",price:0,discount:0,stock:0,active:true};const load=()=>api.get("/products/admin/all").then(r=>setItems(r.data));useEffect(() => {
  load();
}, []);const save=async e=>{e.preventDefault();try{if(edit._id)await api.put(`/products/${edit._id}`,edit);else await api.post("/products",edit);setMsg("Saved successfully");setEdit(null);load()}catch(x){setMsg(x.response?.data?.message||"Save failed")}};const del=async id=>{if(confirm("Delete this product?")){await api.delete(`/products/${id}`);load()}};return <div><div className="admin-top"><div><span className="eyebrow">Inventory</span><h1>Products & stock</h1></div><button className="btn primary" onClick={()=>setEdit(blank)}><Plus/> Add product</button></div>{msg&&<div className="success">{msg}</div>}<div className="admin-table-wrap"><table><thead><tr><th>Product</th><th>Price</th><th>Stock</th><th>Status</th><th>Actions</th></tr></thead><tbody>{items.map(p=><tr key={p._id}><td><div className="table-product"><img src={p.image}/><span>{p.name}<small>{p.category}</small></span></div></td><td>₹{p.price}</td><td><b>{p.stock}</b></td><td><span className={`status ${p.stock<=0?"cancelled":p.stock<=5?"processing":"delivered"}`}>{p.stock<=0?"Out of Stock":p.stock<=5?"Low Stock":"In Stock"}</span></td><td><button className="small-btn" onClick={()=>setEdit(p)}>Edit</button><button className="small-btn danger-text" onClick={()=>del(p._id)}>Delete</button></td></tr>)}</tbody></table></div>{edit&&<div className="modal"><form className="modal-card form-grid" onSubmit={save}><button type="button" className="modal-close" onClick={()=>setEdit(null)}>×</button><h2 className="form-span">{edit._id?"Edit product":"Add product"}</h2>{["name","category","animalCategory","image","description","price","discount","stock"].map(k=><label key={k}>{k}<input type={["price","discount","stock"].includes(k)?"number":"text"} value={edit[k]} onChange={e=>setEdit({...edit,[k]:["price","discount","stock"].includes(k)?Number(e.target.value):e.target.value})}/></label>)}<label className="checkbox form-span"><input type="checkbox" checked={edit.active} onChange={e=>setEdit({...edit,active:e.target.checked})}/> Active product</label><button className="btn primary form-span">Save product</button></form></div>}</div>}

function AnimalManager(){const[items,setItems]=useState([]),[form,setForm]=useState(null);const load=()=>api.get("/animals").then(r=>setItems(r.data));useEffect(() => {
  load();
}, []);const del=async id=>{if(confirm("Delete animal?")){await api.delete(`/animals/${id}`);load()}};return <div><div className="admin-top"><div><span className="eyebrow">Content</span><h1>Animals</h1></div><button className="btn primary" onClick={()=>setForm({name:"",tamilName:"",category:"Livestock",scientificName:"",image:"",shortDescription:"",description:"",lifespan:"",diet:[],housing:"",benefits:[],diseases:[],vaccination:[],care:[],featured:false})}><Plus/> Add animal</button></div><div className="admin-table-wrap"><table><thead><tr><th>Animal</th><th>Category</th><th>Scientific name</th><th>Actions</th></tr></thead><tbody>{items.map(a=><tr key={a._id}><td><div className="table-product"><img src={a.image}/><span>{a.name}<small>{a.tamilName}</small></span></div></td><td>{a.category}</td><td>{a.scientificName}</td><td><button className="small-btn" onClick={()=>setForm(a)}>Edit</button><button className="small-btn danger-text" onClick={()=>del(a._id)}>Delete</button></td></tr>)}</tbody></table></div>{form&&<AnimalModal data={form} close={()=>setForm(null)} done={load}/>}</div>}

function AnimalModal({data,close,done}){const[f,setF]=useState(data);const submit=async e=>{e.preventDefault();const clean={...f,diet:Array.isArray(f.diet)?f.diet:String(f.diet).split(",").map(x=>x.trim()).filter(Boolean),benefits:Array.isArray(f.benefits)?f.benefits:String(f.benefits).split(",").map(x=>x.trim()).filter(Boolean),diseases:Array.isArray(f.diseases)?f.diseases:String(f.diseases).split(",").map(x=>x.trim()).filter(Boolean),vaccination:Array.isArray(f.vaccination)?f.vaccination:String(f.vaccination).split(",").map(x=>x.trim()).filter(Boolean),care:Array.isArray(f.care)?f.care:String(f.care).split(",").map(x=>x.trim()).filter(Boolean)};if(f._id)await api.put(`/animals/${f._id}`,clean);else await api.post("/animals",clean);close();done()};return <div className="modal"><form className="modal-card form-grid" onSubmit={submit}><button type="button" className="modal-close" onClick={close}>×</button><h2 className="form-span">{f._id?"Edit animal":"Add animal"}</h2>{["name","tamilName","category","scientificName","image","shortDescription","description","lifespan","housing"].map(k=><label key={k}>{k}<input value={f[k]||""} onChange={e=>setF({...f,[k]:e.target.value})}/></label>)}{["diet","benefits","diseases","vaccination","care"].map(k=><label key={k}>{k} (comma separated)<input value={Array.isArray(f[k])?f[k].join(", "):f[k]||""} onChange={e=>setF({...f,[k]:e.target.value})}/></label>)}<button className="btn primary form-span">Save animal</button></form></div>}

function OrderManager(){const[items,setItems]=useState([]);const load=()=>api.get("/orders/admin/all").then(r=>setItems(r.data));useEffect(() => {
  load();
}, []);const update=async(id,status)=>{await api.put(`/orders/${id}/status`,{status});load()};return <div><div className="admin-top"><div><span className="eyebrow">Sales</span><h1>Orders</h1></div></div><div className="admin-table-wrap"><table><thead><tr><th>Order</th><th>Customer</th><th>Total</th><th>Payment</th><th>Status</th></tr></thead><tbody>{items.map(o=><tr key={o._id}><td>#{o._id.slice(-8).toUpperCase()}</td><td>{o.user?.name}<small>{o.user?.email}</small></td><td>₹{o.total}</td><td>{o.paymentMethod}</td><td><select value={o.status} onChange={e=>update(o._id,e.target.value)}>{["Pending","Confirmed","Processing","Shipped","Delivered","Cancelled"].map(s=><option key={s}>{s}</option>)}</select></td></tr>)}</tbody></table></div></div>}

function UsersManager(){const[u,setU]=useState([]);useEffect(()=>{api.get("/admin/users").then(r=>setU(r.data))},[]);return <div><div className="admin-top"><div><span className="eyebrow">Accounts</span><h1>Users</h1></div></div><div className="admin-table-wrap"><table><thead><tr><th>Name</th><th>Email</th><th>Phone</th><th>Role</th><th>Joined</th></tr></thead><tbody>{u.map(x=><tr key={x._id}><td>{x.name}</td><td>{x.email}</td><td>{x.phone||"—"}</td><td><span className="admin-badge">{x.role}</span></td><td>{new Date(x.createdAt).toLocaleDateString()}</td></tr>)}</tbody></table></div></div>}

function InquiryManager(){const[i,setI]=useState([]);useEffect(()=>{api.get("/admin/inquiries").then(r=>setI(r.data))},[]);return <div><div className="admin-top"><div><span className="eyebrow">Communication</span><h1>Inquiries</h1></div></div><div className="admin-table-wrap"><table><thead><tr><th>Customer</th><th>Product</th><th>Message</th><th>Status</th></tr></thead><tbody>{i.map(x=><tr key={x._id}><td>{x.name||x.user?.name}<small>{x.phone||x.user?.phone}</small></td><td>{x.product?.name||"General"}</td><td>{x.message}</td><td>{x.status}</td></tr>)}</tbody></table></div></div>}

export default function Admin(){return <Shell/>}
