import { Link } from "react-router-dom"; import { ArrowRight, ShieldCheck, Leaf, ShoppingBag, Sparkles } from "lucide-react"; import {useEffect,useState} from "react"; import api from "../services/api"; import AnimalCard from "../components/AnimalCard"; import ProductCard from "../components/ProductCard";
export default function Home(){const [animals,setAnimals]=useState([]),[products,setProducts]=useState([]); useEffect(()=>{Promise.all([api.get("/animals"),api.get("/products")]).then(([a,p])=>{setAnimals(a.data.slice(0,4));setProducts(p.data.slice(0,4))})},[]);
return <div>
<section className="hero"><div className="hero-copy"><span className="pill"><Sparkles size={15}/> Smarter care for every home</span><h1>Care better.<br/><em>Live together.</em></h1><p>A modern animal knowledge and marketplace platform for families, pet parents and small-scale farmers.</p><div className="hero-actions"><Link className="btn primary" to="/animals">Explore animals <ArrowRight size={18}/></Link><Link className="btn ghost" to="/products">Visit marketplace</Link></div><div className="hero-trust"><span><ShieldCheck/> Secure accounts</span><span><Leaf/> Care-first information</span></div></div><div className="hero-art"><div className="hero-orb">🐄</div><div className="float-card one">🐕 <b>10+ animals</b><small>and growing</small></div><div className="float-card two">🛒 <b>Smart marketplace</b><small>stock-aware shopping</small></div></div></section>
<section className="feature-strip"><div><ShieldCheck/><span><b>Secure login</b><small>JWT-protected accounts</small></span></div><div><ShoppingBag/><span><b>Smart inventory</b><small>Live stock availability</small></span></div><div><Leaf/><span><b>Care resources</b><small>Animal-first guidance</small></span></div></section>
<section className="section"><div className="section-head"><div><span className="eyebrow">Discover</span><h2>Meet our animals</h2></div><Link className="text-link" to="/animals">View all <ArrowRight size={16}/></Link></div><div className="grid animals-grid">{animals.map(a=><AnimalCard key={a._id} animal={a}/>)}</div></section>
<section className="section soft"><div className="section-head"><div><span className="eyebrow">Marketplace</span><h2>Popular essentials</h2></div><Link className="text-link" to="/products">Shop all <ArrowRight size={16}/></Link></div><div className="grid products-grid">{products.map(p=><ProductCard key={p._id} product={p}/>)}</div></section>
<section className="cta"><div><span className="eyebrow">Need a quick answer?</span><h2>Ask our Animal Assistant.</h2><p>Get general educational guidance about nutrition, housing and everyday care.</p></div><Link className="btn light" to="/assistant">Ask AI Assistant <Sparkles size={17}/></Link></section>
</div>}
